apiVersion: v2
name: postiz-app
description: A Social Media Scheduling App (requires external Temporal service)
type: application
version: 1.1.0
appVersion: "v2.13.0"
maintainers:
  - name: jonathan-irvin
    email: offendingcommit@gmail.com
    url: https://linktr.ee/offendingcommit
  - name: jamesread
    email: contact@jread.com
    url: http://jread.com
keywords:
  - social media
  - marketing
  - scheduling
  - queue
  - workflow
home: https://postiz.com
sources:
  - https://github.com/gitroomhq/postiz-app
  - https://github.com/gitroomhq/postiz-helmchart
dependencies:
  - name: postgresql
    version: 18.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: valkey
    version: 5.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    alias: redis
