{{- range $index, $manifest := .Values.extraManifests }}
{{- if gt $index 0 }}
---
{{- end }}
{{- if typeIs "string" $manifest }}
{{ $manifest | trim }}
{{- else }}
{{ toYaml $manifest | trim }}
{{- end }}
{{- end }}
